### ISSUE TITLE
Download file is deleted when saving a modified article

### ISSUE THREAD

**Issue by af9** [BrainforgeUK/plg_fields_bffile#1]
I'm using the bffile-field for attaching downloadable files to my articles. This workds fine.
When I modify an article (without modifying the bffile-field, just the article content), the attached file stored in /media/plg_fields_bffile/com_content.article/ is deleted on saving the article, unfortunately.

I would expect, this only occurs after I hit the red deleting-radiobox next to the filename of the bffile-field.

**Comment by BrainforgeUK** [comment]
Bug fixed in v4.2.0.
https://www.brainforge.co.uk/shop/downloads/product/19-plg_fields_bffile

**Comment by af9** [comment]
Works great! Thx
